
function mostrar(){
    document.getElementById('img').style.display = 'block';
  }
  function ocultar(){
    document.getElementById('img').style.display = 'none';
  }
  function mostrar02(){
    document.getElementById('img02').style.display = 'block';
  }
  function ocultar02(){
    document.getElementById('img02').style.display = 'none';
  }
  function mostrar03(){
    document.getElementById('img03').style.display = 'block';
  }
  function ocultar03(){
    document.getElementById('img03').style.display = 'none';
  }

  
  /*Esto es para el Segundo jugador*/ 
  
function mostrar1(){
  document.getElementById('img1').style.display = 'block';
}
function ocultar1(){
  document.getElementById('img1').style.display = 'none';
}
function mostrar2(){
  document.getElementById('img2').style.display = 'block';
}
function ocultar2(){
  document.getElementById('img2').style.display = 'none';
}
function mostrar3(){
  document.getElementById('img3').style.display = 'block';
}
function ocultar3(){
  document.getElementById('img3').style.display = 'none';
}



